// This file was generated by a script.
// Do not manually edit this file.

import { elements } from "./element.ts"

/**
 * The **`<html>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents the root (top-level element) of an HTML document, so it is also referred to as the `<em>`root element`</em>`. All other elements must be descendants of this element.
 */
export const html = elements.html;

/**
 * The **`<base>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies the base URL to use for all `<em>`relative`</em>` URLs in a document. There can be only one `<base>` element in a document.
 */
export const base = elements.base;

/**
 * The **`<head>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element contains machine-readable information (metadata) about the document, like its [title](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title), [scripts](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script), and [style sheets](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style).
 */
export const head = elements.head;

/**
 * The **`<link>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies relationships between the current document and an external resource.
 * This element is most commonly used to link to CSS, but is also used to establish site icons (both "favicon" style icons and icons for the home screen and apps on mobile devices) among other things.
 */
export const link = elements.link;

/**
 * The **`<meta>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents Metadata that cannot be represented by other HTML meta-related elements, like base, link, script, style or title.
 */
export const meta = elements.meta;

/**
 * The **`<style>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element contains style information for a document, or part of a document. It contains CSS, which is applied to the contents of the document containing the `<style>` element.
 */
export const style = elements.style;

/**
 * The **`<title>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines the document's title that is shown in a Browser's title bar or a page's tab. It only contains text; tags within the element are ignored.
 */
export const title = elements.title;

/**
 * The **`<body>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents the content of an HTML document. There can be only one `<body>` element in a document.
 */
export const body = elements.body;

/**
 * The **`<address>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element indicates that the enclosed HTML provides contact information for a person or people, or for an organization.
 */
export const address = elements.address;

/**
 * The **`<article>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a self-contained composition in a document, page, application, or site, which is intended to be independently distributable or reusable (e.g., in syndication). Examples include: a forum post, a magazine or newspaper article, or a blog entry, a product card, a user-submitted comment, an interactive widget or gadget, or any other independent item of content.
 */
export const article = elements.article;

/**
 * The **`<aside>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a portion of a document whose content is only indirectly related to the document's main content. Asides are frequently presented as sidebars or call-out boxes.
 */
export const aside = elements.aside;

/**
 * The **`<footer>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a footer for its nearest ancestor [sectioning content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#sectioning_content) or [sectioning root](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#sectioning_root) element. A `<footer>` typically contains information about the author of the section, copyright data or links to related documents.
 */
export const footer = elements.footer;

/**
 * The **`<header>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents introductory content, typically a group of introductory or navigational aids. It may contain some heading elements but also a logo, a search form, an author name, and other elements.
 */
export const header = elements.header;

/**
 * The **`<h1>`** to **`<h6>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest.
 */
export const h1 = elements.h1;

/**
 * The **`<h1>`** to **`<h6>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest.
 */
export const h2 = elements.h2;

/**
 * The **`<h1>`** to **`<h6>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest.
 */
export const h3 = elements.h3;

/**
 * The **`<h1>`** to **`<h6>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest.
 */
export const h4 = elements.h4;

/**
 * The **`<h1>`** to **`<h6>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest.
 */
export const h5 = elements.h5;

/**
 * The **`<h1>`** to **`<h6>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) elements represent six levels of section headings. `<h1>` is the highest section level and `<h6>` is the lowest.
 */
export const h6 = elements.h6;

/**
 * The **`<main>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents the dominant content of the body of a document. The main content area consists of content that is directly related to or expands upon the central topic of a document, or the central functionality of an application.
 */
export const main = elements.main;

/**
 * The **`<nav>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a section of a page whose purpose is to provide navigation links, either within the current document or to other documents. Common examples of navigation sections are menus, tables of contents, and indexes.
 */
export const nav = elements.nav;

/**
 * The **`<section>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a generic standalone section of a document, which doesn't have a more specific semantic element to represent it. Sections should always have a heading, with very few exceptions.
 */
export const section = elements.section;

/**
 * The **`<blockquote>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element indicates that the enclosed text is an extended quotation. Usually, this is rendered visually by indentation (see [Notes](https://developer.mozilla.org/#usage_notes) for how to change it). A URL for the source of the quotation may be given using the **cite** attribute, while a text representation of the source can be given using the cite element.
 */
export const blockquote = elements.blockquote;

/**
 * The **`<dd>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element provides the description, definition, or value for the preceding term (dt) in a description list (dl).
 */
export const dd = elements.dd;

/**
 * The **`<div>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is the generic container for flow content. It has no effect on the content or layout until styled in some way using CSS (e.g. styling is directly applied to it, or some kind of layout model like [Flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout) is applied to its parent element).
 */
export const div = elements.div;

/**
 * The **`<dl>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a description list. The element encloses a list of groups of terms (specified using the dt element) and descriptions (provided by dd elements). Common uses for this element are to implement a glossary or to display metadata (a list of key-value pairs).
 */
export const dl = elements.dl;

/**
 * The **`<dt>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies a term in a description or definition list, and as such must be used inside a dl element. It is usually followed by a dd element; however, multiple `<dt>` elements in a row indicate several terms that are all defined by the immediate next dd element.
 */
export const dt = elements.dt;

/**
 * The **`<figcaption>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a caption or legend describing the rest of the contents of its parent figure element.
 */
export const figcaption = elements.figcaption;

/**
 * The **`<figure>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents self-contained content, potentially with an optional caption, which is specified using the figcaption element. The figure, its caption, and its contents are referenced as a single unit.
 */
export const figure = elements.figure;

/**
 * The **`<hr>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a thematic break between paragraph-level elements: for example, a change of scene in a story, or a shift of topic within a section.
 */
export const hr = elements.hr;

/**
 * The **`<li>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to represent an item in a list. It must be contained in a parent element: an ordered list (ol), an unordered list (ul), or a menu (menu). In menus and unordered lists, list items are usually displayed using bullet points. In ordered lists, they are usually displayed with an ascending counter on the left, such as a number or letter.
 */
export const li = elements.li;

/**
 * The **`<menu>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is described in the HTML specification as a semantic alternative to ul, but treated by browsers (and exposed through the accessibility tree) as no different than ul. It represents an unordered list of items (which are represented by li elements).
 */
export const menu = elements.menu;

/**
 * The **`<ol>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents an ordered list of items — typically rendered as a numbered list.
 */
export const ol = elements.ol;

/**
 * The **`<p>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a paragraph. Paragraphs are usually represented in visual media as blocks of text separated from adjacent blocks by blank lines and/or first-line indentation, but HTML paragraphs can be any structural grouping of related content, such as images or form fields.
 */
export const p = elements.p;

/**
 * The **`<pre>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents preformatted text which is to be presented exactly as written in the HTML file. The text is typically rendered using a non-proportional, or [monospaced](https://en.wikipedia.org/wiki/Monospaced_font%22%20class=%22external%22%20rel=%22%20noopener), font. Whitespace inside this element is displayed as written.
 */
export const pre = elements.pre;

/**
 * The **`<ul>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents an unordered list of items, typically rendered as a bulleted list.
 */
export const ul = elements.ul;

/**
 * The **`<a>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element (or `<em>`anchor`</em>` element), with [its href attribute](https://developer.mozilla.org/#attr-href), creates a hyperlink to web pages, files, email addresses, locations in the same page, or anything else a URL can address.
 */
export const a = elements.a;

/**
 * The **`<abbr>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents an abbreviation or acronym.
 */
export const abbr = elements.abbr;

/**
 * The **`<b>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to draw the reader's attention to the element's contents, which are not otherwise granted special importance. This was formerly known as the Boldface element, and most browsers still draw the text in boldface. However, you should not use `<b>` for styling text; instead, you should use the CSS font-weight property to create boldface text, or the strong element to indicate that text is of special importance.
 */
export const b = elements.b;

/**
 * The **`<bdi>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element tells the browser's bidirectional algorithm to treat the text it contains in isolation from its surrounding text. It's particularly useful when a website dynamically inserts some text and doesn't know the directionality of the text being inserted.
 */
export const bdi = elements.bdi;

/**
 * The **`<bdo>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element overrides the current directionality of text, so that the text within is rendered in a different direction.
 */
export const bdo = elements.bdo;

/**
 * The **`<br>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element produces a line break in text (carriage-return). It is useful for writing a poem or an address, where the division of lines is significant.
 */
export const br = elements.br;

/**
 * The **`<cite>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to describe a reference to a cited creative work, and must include the title of that work. The reference may be in an abbreviated form according to context-appropriate conventions related to citation metadata.
 */
export const cite = elements.cite;

/**
 * The **`<code>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element displays its contents styled in a fashion intended to indicate that the text is a short fragment of computer code. By default, the content text is displayed using the user agent default monospace font.
 */
export const code = elements.code;

/**
 * The **`<data>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element links a given piece of content with a machine-readable translation. If the content is time- or date-related, the time element must be used.
 */
export const data = elements.data;

/**
 * The **`<dfn>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to indicate the term being defined within the context of a definition phrase or sentence. The p element, the dt/dd pairing, or the section element which is the nearest ancestor of the `<dfn>` is considered to be the definition of the term.
 */
export const dfn = elements.dfn;

/**
 * The **`<em>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element marks text that has stress emphasis. The `<em>` element can be nested, with each level of nesting indicating a greater degree of emphasis.
 */
export const em = elements.em;

/**
 * The **`<i>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a range of text that is set off from the normal text for some reason, such as idiomatic text, technical terms, taxonomical designations, among others. Historically, these have been presented using italicized type, which is the original source of the `<i>` naming of this element.
 */
export const i = elements.i;

/**
 * The **`<kbd>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a span of inline text denoting textual user input from a keyboard, voice input, or any other text entry device. By convention, the user agent defaults to rendering the contents of a `<kbd>` element using its default monospace font, although this is not mandated by the HTML standard.
 */
export const kbd = elements.kbd;

/**
 * The **`<mark>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents text which is **marked** or **highlighted** for reference or notation purposes, due to the marked passage's relevance or importance in the enclosing context.
 */
export const mark = elements.mark;

/**
 * The **`<q>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element indicates that the enclosed text is a short inline quotation. Most modern browsers implement this by surrounding the text in quotation marks. This element is intended for short quotations that don't require paragraph breaks; for long quotations use the blockquote element.
 */
export const q = elements.q;

/**
 * The **`<rp>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to provide fall-back parentheses for browsers that do not support display of ruby annotations using the ruby element. One `<rp>` element should enclose each of the opening and closing parentheses that wrap the rt element that contains the annotation's text.
 */
export const rp = elements.rp;

/**
 * The **`<rt>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies the ruby text component of a ruby annotation, which is used to provide pronunciation, translation, or transliteration information for East Asian typography. The `<rt>` element must always be contained within a ruby element.
 */
export const rt = elements.rt;

/**
 * The **`<ruby>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents small annotations that are rendered above, below, or next to base text, usually used for showing the pronunciation of East Asian characters. It can also be used for annotating other kinds of text, but this usage is less common.
 */
export const ruby = elements.ruby;

/**
 * The **`<s>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element renders text with a strikethrough, or a line through it. Use the `<s>` element to represent things that are no longer relevant or no longer accurate. However, `<s>` is not appropriate when indicating document edits; for that, use the del and ins elements, as appropriate.
 */
export const s = elements.s;

/**
 * The **`<samp>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to enclose inline text which represents sample (or quoted) output from a computer program. Its contents are typically rendered using the browser's default monospaced font (such as [Courier](https://en.wikipedia.org/wiki/Courier_(typeface)%22%20class=%22external%22%20rel=%22%20noopener) or Lucida Console).
 */
export const samp = elements.samp;

/**
 * The **`<small>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents side-comments and small print, like copyright and legal text, independent of its styled presentation. By default, it renders text within it one font-size smaller, such as from small to x-small.
 */
export const small = elements.small;

/**
 * The **`<span>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is a generic inline container for phrasing content, which does not inherently represent anything. It can be used to group elements for styling purposes (using the class or id attributes), or because they share attribute values, such as lang. It should be used only when no other semantic element is appropriate. `<span>` is very much like a div element, but div is a [block-level element](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements) whereas a `<span>` is an [inline element](https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements).
 */
export const span = elements.span;

/**
 * The **`<strong>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element indicates that its contents have strong importance, seriousness, or urgency. Browsers typically render the contents in bold type.
 */
export const strong = elements.strong;

/**
 * The **`<sub>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies inline text which should be displayed as subscript for solely typographical reasons. Subscripts are typically rendered with a lowered baseline using smaller text.
 */
export const sub = elements.sub;

/**
 * The **`<sup>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies inline text which is to be displayed as superscript for solely typographical reasons. Superscripts are usually rendered with a raised baseline using smaller text.
 */
export const sup = elements.sup;

/**
 * The **`<time>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a specific period in time. It may include the datetime attribute to translate dates into machine-readable format, allowing for better search engine results or custom features such as reminders.
 */
export const time = elements.time;

/**
 * The **`<u>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a span of inline text which should be rendered in a way that indicates that it has a non-textual annotation. This is rendered by default as a simple solid underline, but may be altered using CSS.
 */
export const u = elements.u;

/**
 * The **`<wbr>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a word break opportunity—a position within text where the browser may optionally break a line, though its line-breaking rules would not otherwise create a break at that location.
 */
export const wbr = elements.wbr;

/**
 * The **`<area>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines an area inside an image map that has predefined clickable areas. An `<em>`image map`</em>` allows geometric areas on an image to be associated with Hyperlink.
 */
export const area = elements.area;

/**
 * The **`<audio>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to embed sound content in documents. It may contain one or more audio sources, represented using the src attribute or the source element: the browser will choose the most suitable one. It can also be the destination for streamed media, using a MediaStream.
 */
export const audio = elements.audio;

/**
 * The **`<img>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element embeds an image into the document.
 */
export const img = elements.img;

/**
 * The **`<map>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used with area elements to define an image map (a clickable link area).
 */
export const map = elements.map;

/**
 * The **`<track>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used as a child of the media elements, audio and video. It lets you specify timed text tracks (or time-based data), for example to automatically handle subtitles. The tracks are formatted in [WebVTT format](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API) (.vtt files) — Web Video Text Tracks.
 */
export const track = elements.track;

/**
 * The **`<video>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element embeds a media player which supports video playback into the document. You can use `<video>` for audio content as well, but the audio element may provide a more appropriate user experience.
 */
export const video = elements.video;

/**
 * The **`<embed>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element embeds external content at the specified point in the document. This content is provided by an external application or other source of interactive content such as a browser plug-in.
 */
export const embed = elements.embed;

/**
 * The **`<iframe>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a nested browsing context, embedding another HTML page into the current one.
 */
export const iframe = elements.iframe;

/**
 * The **`<object>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents an external resource, which can be treated as an image, a nested browsing context, or a resource to be handled by a plugin.
 */
export const object = elements.object;

/**
 * The **`<picture>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element contains zero or more source elements and one img element to offer alternative versions of an image for different display/device scenarios.
 */
export const picture = elements.picture;

/**
 * The **`<portal>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element enables the embedding of another HTML page into the current one for the purposes of allowing smoother navigation into new pages.
 */
export const portal = elements.portal;

/**
 * The **`<source>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies multiple media resources for the picture, the audio element, or the video element. It is an empty element, meaning that it has no content and does not have a closing tag. It is commonly used to offer the same media content in multiple file formats in order to provide compatibility with a broad range of browsers given their differing support for [image file formats](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types) and [media file formats](https://developer.mozilla.org/en-US/docs/Web/Media/Formats).
 */
export const source = elements.source;

/**
 *
 * The svg element is a container that defines a new
 * coordinate system and
 * [viewport](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox). It is used
 * as the outermost element of SVG documents, but it can also be used to
 * embed an SVG fragment inside an SVG or HTML document.
 *
 */
export const svg = elements.svg;

/**
 *
 * The top-level element in MathML is `<math>`. Every valid
 * MathML instance must be wrapped in `<math>` tags. In
 * addition you must not nest a second `<math>` element in
 * another, but you can have an arbitrary number of other child elements in
 * it.
 *
 */
export const math = elements.math;

/**
 * Use the **HTML `<canvas>` element** with either the [canvas scripting API](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) or the [WebGL API](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API) to draw graphics and animations.
 */
export const canvas = elements.canvas;

/**
 * The **`<noscript>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines a section of HTML to be inserted if a script type on the page is unsupported or if scripting is currently turned off in the browser.
 */
export const noscript = elements.noscript;

/**
 * The **`<script>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to embed executable code or data; this is typically used to embed or refer to JavaScript code. The `<script>` element can also be used with other languages, such as [WebGL](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API)'s GLSL shader programming language and [JSON](https://developer.mozilla.org/en-US/docs/Glossary/JSON).
 */
export const script = elements.script;

/**
 * The **`<del>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a range of text that has been deleted from a document. This can be used when rendering "track changes" or source code diff information, for example. The ins element can be used for the opposite purpose: to indicate text that has been added to the document.
 */
export const del = elements.del;

/**
 * The **`<ins>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a range of text that has been added to a document. You can use the del element to similarly represent a range of text that has been deleted from the document.
 */
export const ins = elements.ins;

/**
 * The **`<caption>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies the caption (or title) of a table.
 */
export const caption = elements.caption;

/**
 * The **`<col>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines a column within a table and is used for defining common semantics on all common cells. It is generally found within a colgroup element.
 */
export const col = elements.col;

/**
 * The **`<colgroup>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines a group of columns within a table.
 */
export const colgroup = elements.colgroup;

/**
 * The **`<table>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents tabular data — that is, information presented in a two-dimensional table comprised of rows and columns of cells containing data.
 */
export const table = elements.table;

/**
 * The **`<tbody>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element encapsulates a set of table rows (tr elements), indicating that they comprise the body of the table (table).
 */
export const tbody = elements.tbody;

/**
 * The **`<td>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines a cell of a table that contains data. It participates in the `<em>`table model`</em>`.
 */
export const td = elements.td;

/**
 * The **`<tfoot>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines a set of rows summarizing the columns of the table.
 */
export const tfoot = elements.tfoot;

/**
 * The **`<th>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines a cell as header of a group of table cells. The exact nature of this group is defined by the scope and headers attributes.
 */
export const th = elements.th;

/**
 * The **`<thead>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines a set of rows defining the head of the columns of the table.
 */
export const thead = elements.thead;

/**
 * The **`<tr>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element defines a row of cells in a table. The row's cells can then be established using a mix of td (data cell) and th (header cell) elements.
 */
export const tr = elements.tr;

/**
 * The **`<button>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is an interactive element activated by a user with a mouse, keyboard, finger, voice command, or other assistive technology. Once activated, it then performs a programmable action, such as submitting a [form](https://developer.mozilla.org/en-US/docs/Learn/Forms) or opening a dialog.
 */
export const button = elements.button;

/**
 * The **`<datalist>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element contains a set of option elements that represent the permissible or recommended options available to choose from within other controls.
 */
export const datalist = elements.datalist;

/**
 * The **`<fieldset>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to group several controls as well as labels (label) within a web form.
 */
export const fieldset = elements.fieldset;

/**
 * The **`<form>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a document section containing interactive controls for submitting information.
 */
export const form = elements.form;

/**
 * The **`<input>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to create interactive controls for web-based forms in order to accept data from the user; a wide variety of types of input data and control widgets are available, depending on the device and user agent. The `<input>` element is one of the most powerful and complex in all of HTML due to the sheer number of combinations of input types and attributes.
 */
export const input = elements.input;

/**
 * The **`<label>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a caption for an item in a user interface.
 */
export const label = elements.label;

/**
 * The **`<legend>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a caption for the content of its parent fieldset.
 */
export const legend = elements.legend;

/**
 * The **`<meter>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents either a scalar value within a known range or a fractional value.
 */
export const meter = elements.meter;

/**
 * The **`<optgroup>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element creates a grouping of options within a select element.
 */
export const optgroup = elements.optgroup;

/**
 * The **`<option>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is used to define an item contained in a select, an optgroup, or a datalist element. As such, `<option>` can represent menu items in popups and other lists of items in an HTML document.
 */
export const option = elements.option;

/**
 * The **`<output>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is a container element into which a site or app can inject the results of a calculation or the outcome of a user action.
 */
export const output = elements.output;

/**
 * The **`<progress>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element displays an indicator showing the completion progress of a task, typically displayed as a progress bar.
 */
export const progress = elements.progress;

/**
 * The **`<select>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a control that provides a menu of options.
 */
export const select = elements.select;

/**
 * The **`<textarea>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a multi-line plain-text editing control, useful when you want to allow users to enter a sizeable amount of free-form text, for example a comment on a review or feedback form.
 */
export const textarea = elements.textarea;

/**
 * The **`<details>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element creates a disclosure widget in which information is visible only when the widget is toggled into an "open" state. A summary or label must be provided using the summary element.
 */
export const details = elements.details;

/**
 * The **`<dialog>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element represents a dialog box or other interactive component, such as a dismissible alert, inspector, or subwindow.
 */
export const dialog = elements.dialog;

/**
 * The **`<summary>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element specifies a summary, caption, or legend for a details element's disclosure box. Clicking the `<summary>` element toggles the state of the parent `<details>` element open and closed.
 */
export const summary = elements.summary;

/**
 * The **`<slot>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element—part of the [Web Components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) technology suite—is a placeholder inside a web component that you can fill with your own markup, which lets you create separate DOM trees and present them together.
 */
export const slot = elements.slot;

/**
 * The **`<template>`** [HTML](https://developer.mozilla.org/en-US/docs/Web/HTML) element is a mechanism for holding HTML that is not to be rendered immediately when a page is loaded but may be instantiated subsequently during runtime using JavaScript.
 */
export const template = elements.template;