import { DOMParser } from "https://deno.land/x/deno_dom@v0.1.12-alpha/deno-dom-wasm.ts";

import { getSpecialType } from "./util/getSpecialType.ts";
import * as typer from "./util/hypertyper.ts";

const html = await fetch("https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes").then(res => res.text());

const document = new DOMParser().parseFromString(html, "text/html")!;

type Attribute = { prop: string; elements: string[]; desc: string; type: string };

const groupByList = (xs: Attribute[]) =>
	xs.reduce((acc, curr) => {
		for (const element of curr.elements) {
			(acc[element] || (acc[element] = [])).push({
				prop: curr.prop,
				elements: curr.elements,
				type: "string",
				desc: curr.desc,
			});
		}

		return acc;
	}, {} as Record<string, Attribute[]>);

const { "Global attribute": globalAttr, ...elements } = groupByList(
	[...document.querySelector("article table.standard-table tbody")?.childNodes!]
		.filter(tr => tr.nodeName === "TR")
		.filter(
			tr =>
				// @ts-ignore: innerHTML exists, but isn't typed
				!(tr.innerHTML as string).includes(`"icon icon-deprecated"`),
		)
		.map(tr => [...tr.childNodes!].map(each => each.textContent))
		.map(([, attr, , elems, , desc]) => {
			const elements = elems
				.replaceAll(/<|>/g, "")
				.split(/,\s+/)
				.map(e => e.trim());

			return {
				type: "", // will be replaced after
				prop: attr.trim(),
				elements,
				desc: desc.trim(),
			};
		})
		.filter(each => each.prop !== "data-*")
		.sort((a, b) => a.prop.localeCompare(b.prop)),
);

const customDesc: Record<string, string> = {
	height: "Specifies the height of the element.",
	width: "Specifies the width of the element.",
};

const composeCustom = (attr: Attribute, element?: string) => ({
	prop: attr.prop,
	desc: customDesc[attr.prop] || attr.desc.replace("\n\n", "\n"),
	type: getSpecialType(attr.prop)(element || "global") || "string",
});

const globalType = typer.type("GlobalAttrs", typer.struct(globalAttr.map(attr => composeCustom(attr))));

const capitalise = (name: string) => name[0].toUpperCase() + name.slice(1);
const toElementAttrType = (name: string) => capitalise(name) + "Attributes";

function* elementTypes() {
	const sorted = Object.keys(elements).sort((a, b) => a.localeCompare(b));
	for (const element of sorted) {
		yield typer.statement(
			typer.type(toElementAttrType(element), typer.struct(elements[element].map(attr => composeCustom(attr, element)))),
		);
	}

	yield typer.statement(
		typer.type(
			"UniqueElementAttrs",
			typer.struct(sorted.map(element => ({ prop: element, type: toElementAttrType(element) }))),
		),
	);
}

export const preamble = "// This file was generated by hypertyper. Do not manually edit this file.";

export const imports = [
	`import { Element } from "./elements.ts";`,
	`import { AriaRoles, AriaAttributes } from "./aria.ts";`,
	`import { HTMLElement, DOMEvents } from "./dom.ts";`,
	`import { Falsy } from "../util.ts";`,
	`type MaybeString = string | Falsy;`,
].join("\n");

const prologue = `
type PropOr<T, P extends string | symbol | number, D> =
	T extends Record<P, infer V> ? V : D;

type Deunionise<T> =
	| ([undefined] extends [T] ? undefined : never)
	| { [K in T extends unknown ? keyof T : never]: PropOr<NonNullable<T>, K, undefined>; };

export type AllAttrs = Partial<Deunionise<UniqueElementAttrs[keyof UniqueElementAttrs]>>;

export type DataAttr = ${"`data-${string}`"};

type MappedPartial<T> = {} & { [P in keyof T]?: T[P] };

export type Attr<E extends Element = Element> =
	MappedPartial<
		GlobalAttrs & { // [data in DataAttr]?: string } & { // TS weirdly breaks when we allow this
			/**
			 * ref callback is called on mount of element with the DOM element.
			 */
			ref: (el: HTMLElement) => void,
			/**
			 * When the element lacks suitable ARIA-semantics, authors must
			 * assign an ARIA-role. Addition of ARIA semantics only exposes
			 * extra information to a browser's accessibility API, and does
			 * not affect a page's DOM.
			 * 
			 * @see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques
			 */
			role: AriaRoles;
			/**
			 * ARIA is a set of attributes that define ways to make web content
			 * and web applications (especially those developed with JavaScript)
			 * more accessible to people with disabilities.
			 * 
			 * @see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA
			 */
			aria: AriaAttributes;
		} & (UniqueElementAttrs & { [k: string]: unknown })[E] & DOMEvents
	>;
`.trim();

typer.writer("./hyper/lib/attributes.ts", typer.program([preamble, imports, globalType, ...elementTypes(), prologue]));
